import requests

s = requests.session()
# 更新
update_body = {
    "domainAccount": "zhao.li2",
    "busSysGroup": {
        "1": "443001",
        "2": "443001",
        "5": "444501"
    },
    "address": "",
    "bakPhone": "",
    "businessTypeA": 0,
    "businessTypeB": 0,
    "businessTypeC": 0,
    "businessTypeD": 0,
    "channelCode": "",
    "city": "",
    "comment": "",
    "companyId": 41, "depId": 73,
    "device": null,
    "dtEntryTime": "2021-12-06 13:47:41",
    "dtQuitTime": null,
    "empCardName": "李昭",
    "empCardNo": "",
    "empId": 12392,
    "empName": "李昭",
    "empNo": "",
    "empStaId": 2,
    "empUid": null,
    "empUserId": 2100140,
    "gender": "0",
    "groId": 3,
    "hasPhone": "1",
    "headEmpId": null,
    "ipAddress": "",
    "isBindIp": "0",
    "maxim": "",
    "oaNumber": "919328",
    "phone": "16634412766",
    "email": "",
    "position": "",
    "postCode": "",
    "proId": null,
    "probationMonth": null,
    "qq": null,
    "regId": 1,
    "selectedRoles": "20001",
    "sysGroup": "443001",
    "sysTelNo": "607071",
    "sysTelPwd": "123654",
    "userName": "lizhao",
    "workAddress": 0,
    "isReceive": 0,
    "phoneExt": "800347"
}
